#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.5.0
# from Racc grammar file "".
#

require 'racc/parser.rb'

  require "#{File.dirname(__FILE__)}/lexer.rb"
  require "#{File.dirname(__FILE__)}/nodes.rb"

class Parser < Racc::Parser

module_eval(<<'...end grammar.y.rb/module_eval...', 'grammar.y.rb', 75)
  def parse(code, show_tokens=false)
    @tokens = Lexer.new.tokenize(code)
    puts @tokens.inspect if show_tokens
    do_parse
  end
  
  def next_token
    @tokens.shift
  end

  def on_error(*e)
    x = e[1] == '$' ? 'End of file' : e[1]
    puts "Invalid Syntax: '#{x}'"
    exit
  end
  
...end grammar.y.rb/module_eval...
##### State transition tables begin ###

racc_action_table = [
     6,    12,    32,    10,     6,    12,    20,    10,     6,    12,
     5,    10,    25,    11,    36,     6,    12,    11,    10,     6,
    12,    11,    10,     6,    12,    41,    10,    40,    11,    25,
     6,    12,    11,    10,     6,    12,    11,    10,     6,    12,
    22,    10,    20,    11,    26,     6,    12,    11,    10,     6,
    12,    11,    10,    20,    15,    18,    19,    20,    11,    18,
    19,    20,    11,    18,    19,    16,    17,    13,    33,    20,
    34,    18,    19,    16,    17,    20,   nil,    18,    19,    16,
    17,    20,   nil,    18,    19,    16,    17,    20,   nil,    18,
    19,    16,    17,    20,   nil,    18,    19,    16,    17,    20,
   nil,    18,    19,    16,    17 ]

racc_action_check = [
    25,    25,    20,    25,    41,    41,    31,    41,     0,     0,
     0,     0,    32,    25,    25,    19,    19,    41,    19,     5,
     5,     0,     5,    18,    18,    37,    18,    37,    19,    12,
    11,    11,     5,    11,    33,    33,    18,    33,    16,    16,
    10,    16,    30,    11,    13,    14,    14,    33,    14,    17,
    17,    16,    17,    29,     2,    29,    29,    28,    14,    28,
    28,    23,    17,    23,    23,    23,    23,     1,    22,     3,
    23,     3,     3,     3,     3,    39,   nil,    39,    39,    39,
    39,    21,   nil,    21,    21,    21,    21,    27,   nil,    27,
    27,    27,    27,    35,   nil,    35,    35,    35,    35,    42,
   nil,    42,    42,    42,    42 ]

racc_action_pointer = [
     6,    67,    50,    62,   nil,    17,   nil,   nil,   nil,   nil,
    37,    28,    14,    44,    43,   nil,    36,    47,    21,    13,
    -1,    74,    62,    54,   nil,    -2,   nil,    80,    50,    46,
    35,    -1,    -3,    32,   nil,    86,   nil,    11,   nil,    68,
   nil,     2,    92 ]

racc_action_default = [
    -1,   -27,    -2,    -3,    -6,   -26,    -8,    -9,   -10,   -11,
   -27,   -27,   -18,   -27,    -5,   -26,   -27,   -27,   -27,   -27,
   -27,    -7,   -27,   -27,   -20,   -27,    43,    -4,   -14,   -15,
   -16,   -17,   -19,   -27,   -13,   -24,   -22,   -27,   -21,   -12,
   -23,   -27,   -25 ]

racc_goto_table = [
     3,    24,     4,     2,    14,    21,    37,     1,   nil,   nil,
   nil,    23,   nil,   nil,    27,   nil,    28,    29,    30,    31,
   nil,    38,   nil,   nil,   nil,    35,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    39,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    42 ]

racc_goto_check = [
     3,     8,     4,     2,     4,     3,     9,     1,   nil,   nil,
   nil,     3,   nil,   nil,     3,   nil,     3,     3,     3,     3,
   nil,     8,   nil,   nil,   nil,     3,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     3 ]

racc_goto_pointer = [
   nil,     7,     3,     0,     2,   nil,   nil,   nil,   -11,   -19 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,     7,     8,     9,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 18, :_reduce_1,
  1, 18, :_reduce_2,
  1, 19, :_reduce_3,
  3, 19, :_reduce_4,
  2, 19, :_reduce_5,
  1, 19, :_reduce_6,
  2, 19, :_reduce_7,
  1, 20, :_reduce_8,
  1, 20, :_reduce_none,
  1, 20, :_reduce_none,
  1, 20, :_reduce_none,
  4, 20, :_reduce_12,
  3, 20, :_reduce_13,
  3, 22, :_reduce_14,
  3, 22, :_reduce_15,
  3, 22, :_reduce_16,
  3, 22, :_reduce_17,
  1, 24, :_reduce_18,
  3, 24, :_reduce_19,
  2, 23, :_reduce_20,
  4, 23, :_reduce_21,
  2, 25, :_reduce_22,
  3, 25, :_reduce_23,
  1, 26, :_reduce_24,
  3, 26, :_reduce_25,
  1, 21, :_reduce_26 ]

racc_reduce_n = 27

racc_shift_n = 43

racc_token_table = {
  false => 0,
  :error => 1,
  :INTEGER => 2,
  :IDEN => 3,
  :NEWLINE => 4,
  :DEFINE => 5,
  :AS => 6,
  "." => 7,
  "!" => 8,
  "*" => 9,
  "/" => 10,
  "+" => 11,
  "-" => 12,
  "=" => 13,
  "," => 14,
  "(" => 15,
  ")" => 16 }

racc_nt_base = 17

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "INTEGER",
  "IDEN",
  "NEWLINE",
  "DEFINE",
  "AS",
  "\".\"",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\"=\"",
  "\",\"",
  "\"(\"",
  "\")\"",
  "$start",
  "Program",
  "Expressions",
  "Expression",
  "Terminator",
  "Operation",
  "Call",
  "Get",
  "Arguments",
  "ArgList" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y.rb', 16)
  def _reduce_1(val, _values, result)
     result = Nodes.new([])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 17)
  def _reduce_2(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 21)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val)
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 22)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 23)
  def _reduce_5(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 24)
  def _reduce_6(val, _values, result)
     result = Nodes.new([])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 25)
  def _reduce_7(val, _values, result)
     result = Nodes.new([val[1]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 29)
  def _reduce_8(val, _values, result)
     result = IntegerNode.new(val[0].to_i)
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

module_eval(<<'.,.,', 'grammar.y.rb', 33)
  def _reduce_12(val, _values, result)
     result = VarAssignNode.new(val[1], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 34)
  def _reduce_13(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 38)
  def _reduce_14(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 39)
  def _reduce_15(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 40)
  def _reduce_16(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 41)
  def _reduce_17(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 45)
  def _reduce_18(val, _values, result)
     result = VarAccessNode.new(nil, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 46)
  def _reduce_19(val, _values, result)
     result = VarAccessNode.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 50)
  def _reduce_20(val, _values, result)
     result = CallNode.new(nil, val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 52)
  def _reduce_21(val, _values, result)
     result = CallNode.new(val[0], val[2], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 56)
  def _reduce_22(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 57)
  def _reduce_23(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 61)
  def _reduce_24(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 62)
  def _reduce_25(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y.rb', 66)
  def _reduce_26(val, _values, result)
     result = val[0]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
